version: '3.6'
services:
  mongo:
    image: mongo:4.4.3-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=fintonic
      - MONGO_INITDB_ROOT_USERNAME=localDeveloper
      - MONGO_INITDB_ROOT_PASSWORD=localDeveloper
