version: '3.7'
services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - ~/apps/mongo:/data/db
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=fintonic
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
